name: build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: repository dispatch
        uses: atxplangl/action-repository-dispatch-caller@main
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO_NAME: "githubactiontest"
          ORG_NAME: "atxplangl"
          EVENT: "qa-event"
          VERSION: "1.2.0"
          GITHUB_SHA: "${{ github.sha }}"
          GITHUB_REF: "${{ github.ref }}"



