name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build docker image, tag, build and push release image
        shell: bash
        run: cat "README.md";sleep 15
      - name: repository dispatch
        uses: atxplangl/action-repository-dispatch-caller@main
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO_NAME: "githubactiontest"
          ORG_NAME: "atxplangl"
          EVENT: "build-event"
          VERSION: "1.1.0"


