name: qa

on:
  repository_dispatch:
    types: [build-event]

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: |
          echo ${{ github.event.client_payload.version }}
          echo ${{ github.event.client_payload.ref }}
          echo ${{ github.event.client_payload.sha }}