name: qa

on:
  workflow_dispatch:
  on:
    repository_dispatch:
      types: [ build-event ]
    branches: [main]
    types:
      - completed

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: echo ${{ github.event.client_payload.version }}
