name: qa

on:
  push:
  workflow_dispatch:
  workflow_run:
    workflows: [test]
    branches: [feature/**]
    types:
      - completed

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build docker image, tag, build and push release image
        shell: bash
        run: echo "qa testing";sleep 15
