name: qa

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:
  workflow_run:
    workflows: [test]
    branches: [main]
    types:
      - completed

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    - name: build docker image, tag, build and push release image
      shell: bash
      run: | echo "qa testing";sleep 15
