name: test

on:
  repository_dispatch:
    types: [test-event]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: |
          echo ${{ github.event.client_payload.version }}
          echo ${{ github.event.client_payload.ref }}
          echo ${{ github.event.client_payload.sha }}
      - name: repository dispatch
        uses: atxplangl/action-repository-dispatch-caller@main
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO_NAME: "githubactiontest"
          ORG_NAME: "atxplangl"
          EVENT: "prod-event"
          VERSION: "${{ github.event.client_payload.version }}"
          GITHUB_SHA: "${{ github.event.client_payload.sha }}"
          GITHUB_REF: "${{ github.event.client_payload.ref }}"