name: test

on:
  workflow_run:
    workflows: [build]
    branches: [feature/**]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build docker image, tag, build and push release image
        shell: bash
        run: echo "testing";sleep 15
